feat(lf): adopt pv from ranger
features of new pv
    1. preview images with chafa
    2. show useful information about EFI files
    3. show mime info about unknown files

diff --git a/private_dot_config/lf/executable_pv b/private_dot_config/lf/executable_pv
--- a/private_dot_config/lf/executable_pv
+++ b/private_dot_config/lf/executable_pv
@@ -1,11 +1,229 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-case "$1" in
-*.tar*) tar tf "$1" ;;
-*.zip) unzip -l "$1" ;;
-*.rar) unrar l "$1" ;;
-*.7z) 7z l "$1" ;;
-*.pdf) pdftotext "$1" - ;;
-*.md) glow -s dark "$1" ;;
-*) highlight -t 4 -O truecolor --force --config-file="${XDG_CONFIG_HOME:-$HOME/.config}/lf/highlight.theme" "$1" ;;
-esac
+set -o noclobber -o noglob -o nounset -o pipefail
+IFS=$'\n'
+
+## Script arguments
+FILE_PATH="${1}" # Full path of the highlighted file
+PV_WIDTH="${2}"  # Width of the preview pane (number of fitting characters)
+## shellcheck disable=SC2034 # PV_HEIGHT is provided for convenience and unused
+PV_IMAGE_ENABLED="True" # 'True' if image previews are enabled, 'False' otherwise.
+
+FILE_EXTENSION="${FILE_PATH##*.}"
+FILE_EXTENSION_LOWER="$(printf "%s" "${FILE_EXTENSION}" | tr '[:upper:]' '[:lower:]')"
+
+## Settings
+HIGHLIGHT_SIZE_MAX=262143 # 256KiB
+HIGHLIGHT_TABWIDTH="${HIGHLIGHT_TABWIDTH:-8}"
+HIGHLIGHT_STYLE="${HIGHLIGHT_STYLE:-pablo}"
+HIGHLIGHT_OPTIONS="--replace-tabs=${HIGHLIGHT_TABWIDTH} --style=${HIGHLIGHT_STYLE} ${HIGHLIGHT_OPTIONS:-}"
+PYGMENTIZE_STYLE="${PYGMENTIZE_STYLE:-autumn}"
+
+handle_extension() {
+	case "${FILE_EXTENSION_LOWER}" in
+	## Archive
+	a | ace | alz | arc | arj | bz | bz2 | cab | cpio | deb | gz | jar | lha | lz | lzh | lzma | lzo | \
+		rpm | rz | t7z | tar | tbz | tbz2 | tgz | tlz | txz | tZ | tzo | war | xpi | xz | Z | zip)
+		atool --list -- "${FILE_PATH}" && exit
+		bsdtar --list --file "${FILE_PATH}" && exit
+		exit 1
+		;;
+	rar)
+		## Avoid password prompt by providing empty password
+		unrar lt -p- -- "${FILE_PATH}" && exit
+		exit 1
+		;;
+	7z)
+		## Avoid password prompt by providing empty password
+		7z l -p -- "${FILE_PATH}" && exit
+		exit 1
+		;;
+
+	## PDF
+	pdf)
+		## Preview as text conversion
+		pdftotext -l 10 -nopgbrk -q -- "${FILE_PATH}" - |
+			fmt -w "${PV_WIDTH}" && exit
+		mutool draw -F txt -i -- "${FILE_PATH}" 1-10 |
+			fmt -w "${PV_WIDTH}" && exit
+		exiftool "${FILE_PATH}" && exit
+		exit 1
+		;;
+
+	## BitTorrent
+	torrent)
+		transmission-show -- "${FILE_PATH}" && exit
+		exit 1
+		;;
+
+	## OpenDocument
+	odt | sxw)
+		## Preview as text conversion
+		odt2txt "${FILE_PATH}" && exit
+		## Preview as markdown conversion
+		pandoc -s -t markdown -- "${FILE_PATH}" && exit
+		exit 1
+		;;
+	ods | odp)
+		## Preview as text conversion (unsupported by pandoc for markdown)
+		odt2txt "${FILE_PATH}" && exit
+		exit 1
+		;;
+
+	## XLSX
+	xlsx)
+		## Preview as csv conversion
+		## Uses: https://github.com/dilshod/xlsx2csv
+		xlsx2csv -- "${FILE_PATH}" && exit
+		exit 1
+		;;
+
+	## HTML
+	htm | html | xhtml)
+		## Preview as text conversion
+		w3m -dump "${FILE_PATH}" && exit
+		lynx -dump -- "${FILE_PATH}" && exit
+		elinks -dump "${FILE_PATH}" && exit
+		pandoc -s -t markdown -- "${FILE_PATH}" && exit
+		;;
+
+	## JSON
+	json)
+		jq --color-output . "${FILE_PATH}" && exit
+		python -m json.tool -- "${FILE_PATH}" && exit
+		;;
+
+	## Jupyter Notebooks
+	ipynb)
+		jupyter nbconvert --to markdown "${FILE_PATH}" --stdout | env COLORTERM=8bit bat --color=always --style=plain --language=markdown && exit
+		jupyter nbconvert --to markdown "${FILE_PATH}" --stdout && exit
+		jq --color-output . "${FILE_PATH}" && exit
+		python -m json.tool -- "${FILE_PATH}" && exit
+		;;
+
+	## Direct Stream Digital/Transfer (DSDIFF) and wavpack aren't detected
+	## by file(1).
+	dff | dsf | wv | wvc)
+		mediainfo "${FILE_PATH}" && exit
+		exiftool "${FILE_PATH}" && exit
+		;; # Continue with next handler on failure
+	esac
+}
+
+handle_image() {
+	local mimetype="${1}"
+	case "${mimetype}" in
+	image/*)
+		chafa "${FILE_PATH}" -s "${PV_WIDTH}x"
+		;;
+	esac
+}
+
+handle_mime() {
+	local mimetype="${1}"
+	case "${mimetype}" in
+	## RTF and DOC
+	text/rtf | *msword)
+		## Preview as text conversion
+		## note: catdoc does not always work for .doc files
+		## catdoc: http://www.wagner.pp.ru/~vitus/software/catdoc/
+		catdoc -- "${FILE_PATH}" && exit
+		exit 1
+		;;
+
+	## DOCX, ePub, FB2 (using markdown)
+	## You might want to remove "|epub" and/or "|fb2" below if you have
+	## uncommented other methods to preview those formats
+	*wordprocessingml.document | */epub+zip | */x-fictionbook+xml)
+		## Preview as markdown conversion
+		pandoc -s -t markdown -- "${FILE_PATH}" && exit
+		exit 1
+		;;
+
+	## E-mails
+	message/rfc822)
+		## Parsing performed by mu: https://github.com/djcb/mu
+		mu view -- "${FILE_PATH}" && exit
+		exit 1
+		;;
+
+	## XLS
+	*ms-excel)
+		## Preview as csv conversion
+		## xls2csv comes with catdoc:
+		##   http://www.wagner.pp.ru/~vitus/software/catdoc/
+		xls2csv -- "${FILE_PATH}" && exit
+		exit 1
+		;;
+
+	## Text
+	text/* | */xml)
+		## Syntax highlight
+		# highlight -t 4 -O truecolor --force --config-file="${XDG_CONFIG_HOME:-$HOME/.config}/lf/highlight.theme" "$1"
+		if [[ "$(stat --printf='%s' -- "${FILE_PATH}")" -gt "${HIGHLIGHT_SIZE_MAX}" ]]; then
+			exit 2
+		fi
+		if [[ "$(tput colors)" -ge 256 ]]; then
+			local pygmentize_format='terminal256'
+			local highlight_format='truecolor'
+		else
+			local pygmentize_format='terminal'
+			local highlight_format='ansi'
+		fi
+		env HIGHLIGHT_OPTIONS="${HIGHLIGHT_OPTIONS}" highlight \
+			--out-format="${highlight_format}" \
+			--config-file="${XDG_CONFIG_HOME:-$HOME/.config}/lf/highlight.theme" \
+			--replace-tab=4 \
+			--force -- "${FILE_PATH}" && exit
+		env COLORTERM=8bit bat --color=always --style="plain" \
+			-- "${FILE_PATH}" && exit
+		pygmentize -f "${pygmentize_format}" -O "style=${PYGMENTIZE_STYLE}" \
+			-- "${FILE_PATH}" && exit
+		exit 2
+		;;
+
+	## DjVu
+	image/vnd.djvu)
+		## Preview as text conversion (requires djvulibre)
+		djvutxt "${FILE_PATH}" | fmt -w "${PV_WIDTH}" && exit
+		exiftool "${FILE_PATH}" && exit
+		exit 1
+		;;
+
+	## Image
+	image/*)
+		## Preview as text conversion
+		# img2txt --gamma=0.6 --width="${PV_WIDTH}" -- "${FILE_PATH}" && exit 4
+		exiftool "${FILE_PATH}" && exit
+		exit 1
+		;;
+
+	## Video and audio
+	video/* | audio/*)
+		mediainfo "${FILE_PATH}" && exit
+		exiftool "${FILE_PATH}" && exit
+		exit 1
+		;;
+
+	## ELF files (executables and shared objects)
+	application/x-executable | application/x-pie-executable | application/x-sharedlib)
+		readelf -WCa "${FILE_PATH}" && exit
+		exit 1
+		;;
+	esac
+}
+
+handle_fallback() {
+	echo '----- File Type Classification -----' && file --dereference --brief -- "${FILE_PATH}" && exit
+	exit 1
+}
+
+MIMETYPE="$(file --dereference --brief --mime-type -- "${FILE_PATH}")"
+if [[ "${PV_IMAGE_ENABLED}" == 'True' ]]; then
+	handle_image "${MIMETYPE}"
+fi
+handle_extension
+handle_mime "${MIMETYPE}"
+handle_fallback
+
+exit 1
